i3-config: /home/tank/.config/i3/config
polybar-config: /home/tank/.config/polybar/config
xresources: /home/tank/.Xresources
nitrogen-config: /home/tank/.config/nitrogen/bg-saved.cfg
wallpaper-path: /home/tank/.config/nitrogen/
